---

# iExport Settings

logLevel: NORMAL # DEBUG, NORMAL, WARNING, ERROR

task:     interactive # see a list of tasks below


parsing:
    xmlFilePath:                  "%USERPROFILE%\\Music\\iTunes\\iTunes Music Library.xml"
    ignoreEmptyPlaylists:         true
    ignoreMaster:                 true
    ignoreNonMusicPlaylists:      true
    ignoreDistinguishedPlaylists: false
    ignorePlaylistsByName:
    # - SomePlaylistName

tasks:
    interactive:  # Ask the user to provide a task name on STDIN and execute this task.
    # (this task has no settings)

    help: # Print usage instructions on STDOUT, including a list of all tasks.
    # (this task has no settings)

    quit: # Exit iExport. Bye!
    # (this task has no settings)

    printLibrary: # Print information about the library, including the playlists and tracks.
    # (this task has no settings)

    printPlaylists: # Print all playlists (folders and actual playlists) in the iTunes library.
    # (this task has no settings)

    printUnlistedTracks: # Print the list of tracks that are not contained in any playlist.
        ignorePlaylists:
        # - SomePlaylistName

    printMultiplyListedTracks: # Print the list of tracks that are contained in more than one playlist.
        ignorePlaylists:
        #    - SomePlaylistName

    generatePlaylists: # Export the iTunes playlists by generating .m3u files at a specified location.
        outputFolder:                 "%USERPROFILE%\\Desktop\\iExport\\Playlists"
        deleteFolder:                 false
        organizeInFolders:            true
        hierarchicalNames:            true
        onlyActualPlaylists:          false
        ignoreDistinguishedPlaylists: false
        ignorePlaylists:
          # - SomePlaylistName
        playlistExtension:            ".m3u8"
        useRelativePaths:             false
        warnSquareBrackets:           true
        slashAsSeparator:             false
        trackVerification:            true
        showContinuousProgress:       true

    exportFiles: # Export the iTunes playlists by creating folders that contain the tracks as files
        outputFolder:                 "%USERPROFILE%\\Desktop\\iExport\\Files"
        deleteFolder:                 false
        hierarchicalNames:            true
        onlyActualPlaylists:          true
        ignoreDistinguishedPlaylists: true
        ignorePlaylists:
          # - SomePlaylistName
        toRootFolder:
          # - SomeOtherPlaylistName
        folderNumbering:              true
        padFolderNumbers:             true
        initialNumber:                1
        trackNumbering:               true
        padTrackNumbers:              true
        normalize:                    true
        showContinuousProgress:       true

...
